# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CodeNotes',
                'doc_host': 'https://MarFerDom.github.io',
                'git_url': 'https://github.com/MarFerDom/CodeNotes',
                'lib_path': 'CodeNotes'},
  'syms': {'CodeNotes.core': {'CodeNotes.core.foo': ('core.html#foo', 'CodeNotes/core.py')}}}