# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_GUI/01_Tk.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/08_GUI/01_Tk.ipynb 3
import tkinter as tk
from tkinter import messagebox, ttk

from functools import partial
