# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_others/03_managing.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_others/03_managing.ipynb 5
from uuid_extensions import uuid7, uuid7str

# %% ../nbs/07_others/03_managing.ipynb 8
from uuid import uuid4
