# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_others/01_structure.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_others/01_structure.ipynb 4
from dataclasses import dataclass, FrozenInstanceError
from typing import List

# %% ../nbs/07_others/01_structure.ipynb 12
import numpy as np
from string import ascii_lowercase as letters
from typing import Callable, List

# %% ../nbs/07_others/01_structure.ipynb 17
from typing import Protocol

# %% ../nbs/07_others/01_structure.ipynb 21
from functools import partial

# %% ../nbs/07_others/01_structure.ipynb 25
from abc import ABC, abstractmethod
