# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_others/08_test_openai.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_others/08_test_openai.ipynb 3
#|eval: false
import openai
import os

from dotenv import load_dotenv, find_dotenv

# %% ../nbs/07_others/08_test_openai.ipynb 9
from IPython.display import display, HTML

# %% ../nbs/07_others/08_test_openai.ipynb 21
import panel as pn  # GUI
