# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_scikit/MFA_tests.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/04_scikit/MFA_tests.ipynb 2
import pandas as pd
import numpy as np

# %% ../nbs/04_scikit/MFA_tests.ipynb 3
from sklearn.decomposition import PCA

# %% ../nbs/04_scikit/MFA_tests.ipynb 18
import matplotlib.pyplot as plt
from sklearn.model_selection import LearningCurveDisplay, train_test_split
from sklearn.tree import DecisionTreeClassifier
